name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wordpress.org/plugins/wp-hamazon/
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NPM
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build package
        run: bash bin/build.sh ${{ github.ref }}

      - name: Deploy to WordPress Directory
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: wp-hamazon
          SVN_USERNAME: ${{ secrets.WPORG_FUMIKI_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_FUMIKI_PASSWORD }}
